### PR TITLE
Test

### PR DESCRIPTION
**Pull request by MichaelOnePlus**

### CODE REVIEW

**Comment by ramswaroop** [comment]
hey @MichaelOnePlus you don't need to send a pull request with your photos. Just upload them to your fork, your website will be up and running.

**Comment by mchlxu** [comment]
Got it. Sorry I am not exactly familiar with this; so made a new account. Although, I have a question. How would I add a category, like another section: photography, music, contact me, film. Things like that. If you can let me know i would greatly appreciate it!


- Thank you :)

**Comment by MichaelOnePlus** [comment]
Got it. Sorry I am not exactly familiar with this. Although, I have a
question. How would I add a category, like another section: photography,
music, contact me, film. Things like that. If you can let me know i would
greatly appreciate it!


- Thank you :)

*Michael Xu*
www.michaelxubox.com
<http://facebook.com/shoesacoustic>  <http://twitter.com/shoesacoustic>
<http://instagram.com/shoesacoustic>
<http://youtube.com/channel/UCRFmeItBt2dssFkUCBr3FHg/videos>
<http://michaelsfieldnotes.wordpress.com.wordpress.com/>

**Comment by ramswaroop** [comment]
Contact me section is there at the bottom, click on "About". For the rest of the things you need an entire blog for yourself it seems.

**Comment by MichaelOnePlus** [comment]
Yes. I understand. Do I have to make another repository to make more
sections? Or do I just make more folders with script for pages?

*Michael Xu*
www.michaelxubox.com
<http://facebook.com/shoesacoustic>  <http://twitter.com/shoesacoustic>
<http://instagram.com/shoesacoustic>
<http://youtube.com/channel/UCRFmeItBt2dssFkUCBr3FHg/videos>
<http://michaelsfieldnotes.wordpress.com.wordpress.com/>

**Pull request closed without merging**
